### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by andyx87** [basilfx/homeassistant-biketrax#81]
Hi there,
since today, I have the following problem.

Error setting up entry BikeTrax ************ for biketrax
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/biketrax/__init__.py", line 87, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'

**Comment by basilfx** [comment]
Thank you for reporting. It seems I have missed a deprecation notice.

Can you see if the following change works for you?

https://github.com/basilfx/homeassistant-biketrax/pull/83/commits/b7284a6fc5ab8244a7fa903e3054fae24fd66a9b

**Comment by andreasbrett** [comment]
> Thank you for reporting. It seems I have missed a deprecation notice.
> 
> Can you see if the following change works for you?
> 
> [b7284a6](https://github.com/basilfx/homeassistant-biketrax/commit/b7284a6fc5ab8244a7fa903e3054fae24fd66a9b)

works on my instance. BikeTrax is now functional again in HA.

**Comment by basilfx** [comment]
Thanks for reporting back. I will create a new release this week to address this issue.

**Comment by malexmave** [comment]
Hi there. First of all, thanks for the addon, it's very helpful for me. I'm currently seeing the same issue - do you have any update when you will create the release? Thanks! :)

**Comment by basilfx** [comment]
The new v1.0.0 release contains a fix for this issue, and works with 2023.5+
